### PR TITLE
WIP: Argparser support with subcommands

### PR DESCRIPTION
**Pull request by MarcoBuster**
Add argparser support with two subcommands: list and book

### CODE REVIEW

**Comment by MarcoBuster** [comment]
@Mroik this pull request is now ready for review

**Comment by Mroik** [comment]
Check the new commit please :smile: @MarcoBuster

**Comment by Mroik** [comment]
yeah... but i can't access it with `args.exclude-day`

**Comment by MarcoBuster** [comment]
> yeah... but i can't access it with `args.exclude-day`

you should be able to. For instance, you can access `--cf-code` with `cf_code`

**Comment by Mroik** [comment]
Yep, works. If everything else is ok I'll merge

**Comment by MarcoBuster** [comment]
LGTM!

**Pull request merged**
